# Generated by Django 4.0.3 on 2022-03-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
